// App/theme.js
export const lightTheme = {
  background: "bg-slate-50",
  navbar: "bg-white",
  sidebar: "bg-slate-200",
  card: "bg-white",
  modal: "bg-white",
  button: "bg-blue-600 text-white",
  buttonHover: "hover:bg-blue-700",
  buttonActive: "bg-blue-800",
  buttonText: "text-white",
  link: "text-blue-600",
  text: "text-slate-900",
  textHover: "hover:text-slate-700",
  secondaryText: "text-slate-700",
  border: "border-slate-200",
  success: "text-green-600",
  danger: "text-red-600",
  mutedText: "text-slate-500",
  chip: "bg-slate-100",
};
  
  export const darkTheme = {
    background: "bg-gray-900",
    navbar: "bg-gray-800",
    sidebar: "bg-neutral-900",
    card: "bg-neutral-900",
    modal: "bg-gray-800",
    button: "bg-white text-black",
    buttonHover: "hover:bg-neutral-200 hover:text-black",
    buttonActive: "bg-blue-400",
    buttonText: "text-white",
    link: "text-blue-400",
    text: "text-white",
    textHover: "",
    secondaryText: "text-gray-300",
    border: "border-gray-600",
    success: "text-green-400",
    danger: "text-red-400",
    mutedText: "text-gray-400",
    chip: "bg-neutral-800",
  };
  